### PR TITLE
chore: moved fix to mainActivity

### PR DESCRIPTION
**Pull request by Budaa**
### Detailed readable description
- fill in... (If you PR includes breaking changes please write it and make sure it was planned)

### Checklist
- [ ] I've provided a readable title for the PR
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### CODE REVIEW

**Review by f-roland — APPROVED** [review]

**Comment by inckie** [comment]
This change breaks preloader: note that there is no more background image and spinner is wrong. I've actually tried that change first, and then moved to second one.

**Comment by f-roland** [comment]
I see. Maybe we can fix the background image & spinner in the preloader for this to work ?

**Comment by inckie** [comment]
I'd better find solution closer to RN view. Since this means we are breaking all resource access by creating inconsistency in the configuration for the entire application.
Proper way to fix that is to actually fix the RN screens library, since there is a special method in RN base context that returns the activity directly, and they don't really need these hacks with dynamic casting parents in the first place.

**Comment by f-roland** [comment]
Fair enough, we can patch the library in a post install script. If you tell us the file to change and diffs (it can even be a git patch) we can take care of the rest

**Comment by inckie** [comment]
@f-roland I'm trying to find a better place. When I hack the RN view alone, all native views are still in system DPI and they were designed to be in hacked one, too, so we now have to hack entire activity.
I will try to find out why resource resolution breaks, since many views are relying on the resource override (loader and splash, push sounds, many plugins with uploadable resources). I assume there is some compat method that overrides the factories and when we call createConfigurationContext we are bypassing it.

**Pull request closed without merging**
