### PR TITLE
feat: add-rn-gesture-handler-lib

### PR DESCRIPTION
**Pull request by f-roland**
### Detailed readable description
This PR is adding the RN gesture handler library

this is following the recommendation from https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava to use the provided wrapper for the react root view

the dependencies should be declared properly, but I'm not 100% sure about the addition to the gradle files

### Checklist
- [ ] I've provided a readable title for the PR
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### CODE REVIEW

**Comment by sherwino** [comment]
Test are failing at the moment because of memory issues:
```
error node_modules/@applicaster/quick-brick-core-plugins/node_modules/@applicaster/quick-brick-tabs/node_modules/ramda/src/dropWhile.js: ENOMEM: not enough memory, read. Run CLI with --verbose flag for more details.
Error: ENOMEM: not enough memory, read
```

**Comment by f-roland** [comment]
@inckie this seems to build & register the module properly with these changes. so it's ready for review

**Comment by inckie** [comment]
@f-roland want to keep it for TV as well? We can disable it just in case, but I don't think there is much impact anyway.

**Review by inckie — APPROVED** [review]

**Comment by f-roland** [comment]
Yeah I don't think it hurts on TV, and it will simplify the integration on the JS side (we don't have to segregate this dependency in the core modules

I asked @sherwino to try it on android to make sure it's working as expected. I did a quick test yesterday which wasn't successful, but it was only on the emulator.

There may be an issue with the integration on the native side:
- the doc mentions that the RNGestureHandlerRootView constructor needs to be invoked with `MainActivity.this` but our MainActivity doesn't extend `ReactActivity`, this is why I tried with `rootActivity` but I'm not sure if this is inline with what the library expects
- they also mention that we should have a ReactActivityDelegate defined on the main activity, but the point is to override the method which provides the reactRootView, and we're essentially doing the same

if Sherwin confirms it doesn't work in this state on android (the JS code works well on iOS), would be great if you can help him out @inckie

**Comment by inckie** [comment]
@f-roland Got it, I'll check library code then, just in case it indeed needs something closer to expo apps, but I think its fine if it builds.

**Comment by f-roland** [comment]
It does build, but the gesture handling doesn't work
@sherwino if you can reach out to @inckie to check this out it would be great.

**Pull request merged**
