### PR TITLE
feat: layoutOrientationChange event

### PR DESCRIPTION
**Pull request by inckie**
### Detailed readable description

New event `layoutOrientationChange` added, that fired when layout orientation changes (different from `orientationChange` which is fired when device is physically rotated).
Will only report portrait and landscape (i.e. no reversed ones, since layout can only be one of these 2), but this should be enough for our purposes.
We can extract render layer orientation to fix it, but it has some complications on some tablets.

https://applicaster.monday.com/boards/1141653998/pulses/1656814264/posts/1155962230

### Checklist
- [x] I've provided a readable title for the PR
- [x] I've provided a detailed description
- [x] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

- [x] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

- [x] My PR is a part of a new feature or a feature improvement
    - [x] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### CODE REVIEW

**Review by f-roland — APPROVED** [review]
@inckie while it's still not strictly align to the iOS behaviour, with the small tweak I did, it is something we can effectively work for a smooth and reliable user experience.

if that's fine with you, we can merge it

**Comment by inckie** [comment]
@f-roland I'll do a bit of refactoring and merge today, thanks!

**Comment by f-roland** [comment]
Alright.

Please keep the consistent event name and the physicalChange flag - this is key for us to implement what we're missing compared to iOS on the JS side

thanks !

**Review by f-roland — APPROVED** [review]
Great Thanks. can this be merged then ?

**Pull request merged**
