### PR TITLE
feat: forceAppReload method for RN

### PR DESCRIPTION
**Pull request by inckie**
### Detailed readable description

Adding callback to restart the app (react native activity) from QB.

### Checklist
- [x] I've provided a readable title for the PR
- [x] I've provided a detailed description
- [x] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

- [x] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

- [x] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### CODE REVIEW

**Review by f-roland — COMMENTED** [review]
@inckie this seems to be ok for us at this stage.
How can we proceed to merge it to continue the work on the RN side ?

**Comment by inckie** [comment]
@f-roland I'll move bridge to the core and update platform all together with new storage keys for device properties today.

**Comment by f-roland** [comment]
Wouldn't it be better to leave this along the other native modules for QuickBrick ?

**Comment by inckie** [comment]
All the other native modules are in the SDK core actually.
https://github.com/applicaster/applicaster-android-sdk/tree/dev/src/main/java/com/applicaster/reactnative
https://github.com/applicaster/applicaster-android-sdk/tree/dev/src/main/qb/com/applicaster/reactnative
When we will drop legacy, I'll move them to separate library though, so it will be possible to write pure native code without having react libs in the source paths

**Review by ranmeirman — APPROVED** [review]

**Pull request merged**
