### PR TITLE
fix: move density hack to and pass proper context to RN

### PR DESCRIPTION
**Pull request by inckie**
### Detailed readable description

Getting rid of the TV density hack on app level and wrong context passed to RN which causes errors been logged on every RN view creation, and breaks some RN libraries that do not retrieve activity in a proper way (namely navigation and gestures).

### Checklist
- [x] I've provided a readable title for the PR
- [x] I've provided a detailed description
- [x] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

- [x] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [x] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### CODE REVIEW

**Comment by f-roland** [comment]
Thanks @inckie 
In addition, it looks like we need https://github.com/applicaster/zapp-platform-android/blob/a1efe14df33e16924c44ec5bc0afa34b236bbb77/android_quickbrick_app/src/main/java/com/applicaster/ui/activities/MainActivity.kt#L36 to extend ReactCompatActivity

@Budaa is trying it out

**Comment by Budaa** [comment]
The issue still persists.

```2021-07-09 00:27:24.780 8143-8143/com.zappntv E/QuickBrickManager: Exception in ReactContextIn order to use RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity
    java.lang.IllegalStateException: In order to use RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity```

**Comment by inckie** [comment]
@f-roland in fact we dont need. I;ve checked the library source, and they only need FragmentActivity, they just did not update the message. They fixed it for Expo a few years ago.

**Comment by inckie** [comment]
Thats the reason in expo they did it:
https://github.com/expo/expo/blame/41458d1de91544c41097818db21e44e9aa84688c/android/expoview/src/main/java/versioned/host/exp/exponent/ReactUnthemedRootView.java#L13

So I've implemented same approach in the original branch.

**Comment by inckie** [comment]
Ok, now native views that use resources are broken. This original hack created very interesting inconsistency in the app. Layout is happening using hacked metrics, but resources are taken using proper DPI, since activity creates its own themed context with proper values. If we override DPI on Activity level, we start to get corresponding resources resources, i.e. they all double in size. It affects players, for example. Also thats the reason other activities and fragments we create are not distorted (i.e. still in proper TV DPI and not our hacked one).
Given that we indeed must pass activity as a context to the view, since RN designed around this assumption, and on mobile it costed scand and me a few weeks total of issues investigations with libraries like chromecast and native activities (same problem we later hit with gesture hadler and now with navigation, and we have tons or error from react native itself in logs), I assume we better look for totally new approach. So far most promising looks an intermediate container or subclassed RN RootView that will have internal scale 0.5x and adjust measurements accordingly.
Lets put it aside for a bit.

**Comment by inckie** [comment]
summarizing what I've found out so far:

- this branch approach has issues with native views resources, since they have parent activity DPI. But child native fragments work correct (since only RN view is hacked)
- Pawel approach breaks resources and all native elements: dialogs, child fragments. For example everything on onetrust screen is tiny and unreadable. I suppose we will have same issues with the this native screens library as well when trying to create child native fragments.
- basic scaling proxy view seems to work, but player in OC takes only 1/4 of the screen. Most likely it's due to old js code used in the plugin, using window instead of dimensions sizes. Need to test on our TV player. Plus, from code PoV its 'hackless' way, we just use custom zoomable container view

**Comment by f-roland** [comment]
@inckie 
> basic scaling proxy view seems to work, but player in OC takes only 1/4 of the screen. Most likely it's due to old js code used in the plugin, using window instead of dimensions sizes. Need to test on our TV player. Plus, from code PoV its 'hackless' way, we just use custom zoomable container view

what's the implementation for this ? are we still passing an activity to the react root view ? do we still need to patch the React Native Screen library ?

**Comment by inckie** [comment]
@f-roland 
I basically add an additional view between RN root and Activity, like that:
```
            AnalyticsAgentUtil.logEvent(AnalyticsAgentUtil.APPLICATION_STARTED)
            val root = AbsoluteLayout(this)
            root.layoutParams = AbsoluteLayout.LayoutParams(
                    (resources.displayMetrics.widthPixels * resources.displayMetrics.density).toInt(),
                    (resources.displayMetrics.heightPixels * resources.displayMetrics.density).toInt(), 0, 0)
            root.scaleX = 1.0f / resources.displayMetrics.density
            root.scaleY = 1.0f / resources.displayMetrics.density
            root.pivotX = 0.0f
            root.pivotY = 0.0f
            val rnView = uiLayer!!.rootView
            rnView.layoutParams = FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT)
            root.addView(rnView)
            setContentView(root)
```
I've used subclassed view initially with layout functions having scale factor inside, but result is the same, so we can take a look at that approach.
In this case we pass activity just as on mobile, no any additional dpi hacks, no patching required, so probably its the best solution.
I still think there is a way to hack resources though, to get same results as we had.
Btw, as I get, this native screen option for navigation library is only needed if we will manage native fragments, or have more than one fragment in RN, which we dont support now anyway, so we can just disable it? But I still better have activity context passed to the root, since its much safer.

**Comment by f-roland** [comment]
This lib is a pre-requisite for the navigation library. if we can't make it work, we can use our navigation library.

if the option you describe does the 3 following things:
1. we pass an activity and not a context to the ReactRootView
2. we have the same scale we have currently on android TV
3. you're happy with it

then I'm buying. I only need 1 & 2 😅

**Comment by Budaa** [comment]
Works well, react-native-screens doesn't crash anymore.

In terms of backward compatibility, I checked on the standard Zappn and Feature app and it seems to work well.

**Review by Budaa — APPROVED** [review]

**Pull request merged**
